import { LexiconRule } from "./types";

/**
 * Recursively freezes an array and any nested objects/arrays so the lexicon
 * cannot be mutated at runtime. Safety: the lexicon is the Tier 1 precedence
 * source (rule 02.3); a runtime mutation could silently weaken a Tier 1 hit.
 */
function deepFreeze<T>(value: T): T {
  if (Array.isArray(value)) {
    Object.freeze(value);
    for (const item of value) {
      deepFreeze(item);
    }
  } else if (value !== null && typeof value === "object") {
    Object.freeze(value);
    for (const key of Object.keys(value)) {
      deepFreeze((value as Record<string, unknown>)[key]);
    }
  }
  return value;
}

export const TIER_1_RULES: readonly LexiconRule[] = deepFreeze([
  {
    category: "respiratory_arrest",
    phrases: [
      "not breathing",
      "stopped breathing",
      "stops breathing",
      "stop breathing",
      "isnt breathing",
      "isn t breathing",
      "arent breathing",
      "aren t breathing",
      "cant breathe",
      "can t breathe",
      "cannot breathe",
      "not able to breathe",
      "struggling to breathe",
      "struggling for breath",
      "struggled for breath",
      "stopped inhaling",
      "blue lips",
      "blue around the lips",
      "turning blue",
      "turned blue",
      "looks blue",
      "turning purple",
      "turned purple",
      "turned grey",
      "ashen colour",
      "suffocating",
      "gasping for air",
      "gasping for breath",
      "barely breathing",
      "shallow breaths",
      "grunting",
      "silent choking",
      "head bobbing with breath",
      "plastic bag over head",
      "caught in blind cord",
      "cord around neck",
      "hanging by cord",
      "chest not moving",
      "cannot cry or make sound",
    ],
  },
  {
    category: "cardiac_arrest",
    phrases: [
      "no pulse",
      "cant feel pulse",
      "can t feel pulse",
      "cannot feel pulse",
      "cant feel a pulse",
      "can t feel a pulse",
      "no heartbeat",
      "heart stopped",
      "heart not beating",
      "heart is not beating",
      "cardiac arrest",
      "cpr",
      "start cpr",
      "chest compressions",
    ],
  },
  {
    category: "choking_obstruction",
    phrases: [
      "choking",
      "choking on",
      "something stuck in throat",
      "stuck in her throat",
      "stuck in his throat",
      "airway blocked",
      "inhaled object",
      "cant swallow saliva",
      "can t swallow saliva",
      "cant cry",
      "can t cry",
      "throat completely swollen",
      "inhaled peanut",
      "swallowed balloon",
      "lodged in windpipe",
    ],
  },
  {
    category: "unresponsiveness",
    phrases: [
      "unconscious",
      "wont wake up",
      "won t wake up",
      "isnt waking up",
      "isn t waking up",
      "cant wake him",
      "can t wake him",
      "cant wake her",
      "can t wake her",
      "cant wake up",
      "can t wake up",
      "cant wake",
      "can t wake",
      "wont respond",
      "won t respond",
      "unresponsive",
      "passed out and wont wake",
      "passed out and won t wake",
      "floppy and unresponsive",
      "in a coma",
      "coma",
      "completely limp",
      "not reacting",
      "not responding at all",
    ],
  },
  {
    category: "severe_trauma_hemorrhage",
    phrases: [
      "severe bleeding",
      "blood spurting",
      "spurting",
      "blood is spurting",
      "deep wound",
      "open fracture",
      "major head trauma",
      "deep cut",
      "crushed",
      "severed",
      "stabbed",
      "stab wound",
      "knife wound",
      "stabbed my child",
      "stabbed my baby",
      "stabbed him",
      "stabbed her",
      "stabbed in the",
      "stabbed with a knife",
      "slashed with a knife",
      "knife attack",
      "cut his throat",
      "cut her throat",
      "throat cut",
      "slit throat",
      "gunshot",
      "bullet wound",
      "gunshot wound",
      "got shot",
      "been shot",
      "shot my child",
      "shot my baby",
      "bleeding heavily",
      "bleeding profusely",
      "bleeding out",
      "wont stop bleeding",
      "won t stop bleeding",
      "blood pouring",
      "pouring with blood",
      "gushing blood",
      "blood everywhere",
      "punctured",
      "impaled",
      "strangled",
      "strangling",
      "smothered",
      "suffocated",
      "choked my baby",
      "choked my child",
      "furniture fell on baby",
      "crushed by tv",
      "run over by car",
      "hit by a car",
      "fell from balcony",
      "fell out of window",
      "thrown down stairs",
      "going to kill my baby",
      "going to drown my baby",
      "shaking my baby violently",
      "about to hurt my child",
      "scalp torn off",
      "decapitated",
      "amputated",
      "severed limb",
    ],
  },
  {
    category: "anaphylaxis",
    phrases: [
      "anaphylaxis",
      "throat closing",
      "throat is closing",
      "swollen tongue and throat",
      "swollen tongue",
      "tongue is swollen",
      "allergic reaction cant breathe",
      "allergic reaction can t breathe",
      "epipen",
      "peanut allergy reaction",
      "injected with pen",
      "allergic reaction face swelling",
    ],
  },
  {
    category: "poisoning_toxic_ingestion",
    phrases: [
      "poisoned",
      "swallowed bleach",
      "drank bleach",
      "bleach",
      "cleaning product",
      "drank cleaning product",
      "ate a battery",
      "swallowed battery",
      "button battery",
      "swallowed button battery",
      "swallowed magnet",
      "swallowed a magnet",
      "eaten mushrooms",
      "poisonous",
      "medicine overdose",
      "swallowed poison",
      "took sleeping pills",
      "took my husbands sleeping pills",
      "took all my medication",
      "took an overdose",
      "taken an overdose",
      "took medication at once",
      "drank vape liquid",
      "nicotine liquid",
      "swallowed vape juice",
      "dishwasher pod",
      "laundry pod",
      "swallowed laundry pod",
      "ate dishwasher tablet",
      "antifreeze",
      "drank antifreeze",
      "weedkiller",
      "drank weedkiller",
      "rat poison",
      "caustic soda",
      "drain unblocker",
      "drank white spirit",
      "swallowed acetone",
      "baby ate cocaine",
      "swallowed cannabis gummies",
      "methadone ingestion",
      "drank lighter fluid",
      "carbon monoxide",
      "gas leak passed out",
      "cyanide",
    ],
  },
  {
    category: "seizure_status",
    phrases: [
      "seizure wont stop",
      "seizure won t stop",
      "continuous fitting",
      "continuously fitting",
      "having seizures",
      "having a seizure",
      "fitting",
      "fit that wont stop",
      "fit that won t stop",
      "seizures",
      "seizure lasting",
      "seizure",
    ],
  },
  {
    category: "suicide_active",
    phrases: [
      "want to die",
      "going to kill myself",
      "want to kill myself",
      "wanna die",
      "suicide",
      "suicidal",
      "end my life",
      "ending my life",
      "going to end my life",
      "take my own life",
      "taking my own life",
      "took my own life",
      "take my life",
      "kill myself",
      "end it all",
      "dont want to live anymore",
      "don t want to live anymore",
      "dont want to be here anymore",
      "don t want to be here anymore",
      "better without me",
      "goodbye letter",
    ],
  },
  {
    category: "self_harm_active",
    phrases: [
      "self harm",
      "self harming",
      "selfharm",
      "selfharming",
      "cutting myself",
      "slashing myself",
      "hurting myself right now",
      "harming myself",
      "bleeding from self harm",
      "took all my pills",
      "took sleeping pills",
      "took all my medication",
    ],
  },
  {
    category: "meningitis_sepsis_emergency",
    phrases: [
      "purple rash",
      "meningitis rash",
      "stiff neck with high fever",
      "grunting with blue skin",
      "glass test",
      "tumbler test",
      "tumbler test failed",
      "rash not fading",
      "non blanching rash",
      "mottled skin",
      "petechiae",
      "purpura",
      "bulging fontanelle with fever",
    ],
  },
  {
    category: "severe_burns",
    phrases: [
      "severe burn",
      "badly burned",
      "badly scalded",
      "chemical burn",
      "large scald",
      "skin peeling off from burn",
      "skin peeling off",
      "burned with boiling water",
      "boiling water",
      "skin peeled",
      "third degree burn",
      "third-degree burn",
      "on fire",
      "set on fire",
      "electric shock",
      "stuck finger in socket",
      "electrocuted",
      "acid attack",
    ],
  },
  {
    category: "drowning_submersion",
    phrases: [
      "drowning",
      "drowned",
      "nearly drowned",
      "submerged in water",
      "submerged",
      "underwater",
      "found in the bath",
      "found in the bath face down",
      "face down in bath",
      "face down in water",
      "inhalation of water",
    ],
  },
]);

export const TIER_2_RULES: readonly LexiconRule[] = deepFreeze([
  {
    category: "infant_fever_under_3m",
    phrases: [
      "fever under 3 months",
      "fever under 3 month",
      "newborn with temperature",
      "baby fever 38",
      "fever of 38",
      "temperature of 38",
      "38 degrees",
      "38 c",
      "38c",
      "6 week old baby fever",
      "6 week old fever",
      "4 week old temperature",
      "under 3 months",
      "under 3 month",
      "39 degrees",
      "39 c",
      "39c",
      "temperature of 39",
      "fever of 39",
      "4 month old fever 39",
      "5 month old fever 39",
      "rigors with fever",
      "shivering with high temperature",
      "fever lasting 5 days",
      "fever for 5 days",
    ],
  },
  {
    category: "dehydration_vomiting",
    phrases: [
      "cant keep fluids down",
      "can t keep fluids down",
      "no wet nappies for 12 hours",
      "no wet nappies",
      "dry nappies all day",
      "sunken fontanelle",
      "no tears when crying",
    ],
  },
  {
    category: "non_emergency_rash",
    phrases: [
      "rash with temperature",
      "spreading red rash",
      "blistering rash",
      "slapped cheek with fever",
    ],
  },
  {
    category: "breathing_stridor_wheeze",
    phrases: [
      "wheezing",
      "stridor",
      "barking cough",
      "fast breathing",
      "ribs pulling in",
      "grunting breath",
    ],
  },
  {
    category: "head_injury_observed",
    phrases: [
      "bumped head vomiting",
      "drowsy after falling",
      "swelling on baby head",
      "fell off changing table",
      "fell off bed vomiting",
    ],
  },
  {
    category: "severe_ear_infection",
    phrases: [
      "pus coming from ear",
      "severe earache fever",
      "swelling behind ear",
      "crying pulling ear fever",
      "severe earache",
    ],
  },
  {
    category: "acute_abdominal_pain",
    phrases: [
      "severe tummy pain",
      "drawing legs up in pain",
      "blood in stool",
      "jelly stool",
      "green vomit",
      "vomiting green bile",
      "bilious vomit",
      "projectile vomiting after feed",
      "blood in vomit",
      "coffee ground vomit",
      "red currant jelly stool",
      "blood and mucus in stool",
      "hard swollen tummy painful",
    ],
  },
  {
    category: "suspected_fracture",
    phrases: [
      "wont put weight on leg",
      "won t put weight on leg",
      "arm swollen after fall",
      "unable to move arm",
      "limping fever",
      "pulled elbow",
      "dislocated arm",
      "bone sticking out",
      "deep cut needs stitches",
    ],
  },
  {
    category: "febrile_seizure_resolved",
    phrases: [
      "febrile fit",
      "short febrile fit",
      "short seizure with fever",
    ],
  },
  {
    category: "eye_infection_injury",
    phrases: [
      "eye swollen shut",
      "yellow discharge from baby eye",
      "yellow discharge",
      "scratched eye",
      "chemical in baby eye",
      "eye swollen red with fever",
      "periorbital swelling",
      "scratch on eyeball",
      "bead stuck in nose",
      "object stuck in ear",
    ],
  },
  {
    category: "testicular_acute_pain",
    phrases: [
      "swollen testicle",
      "testicle pain",
      "testicular pain",
      "swollen scrotum",
      "red swollen groin",
      "groin lump painful",
    ],
  },
]);

export const TIER_3_RULES: readonly LexiconRule[] = deepFreeze([
  {
    category: "physical_abuse",
    phrases: [
      "hit the baby",
      "shook the baby",
      "partner hits child",
      "bruises on baby",
      "slapped child",
      "belted child",
      "hits child with a belt",
      "cigarette burns on baby",
      "bite mark on toddler",
      "bruises on 2 month old",
      "black eye on infant",
      "shook the pram violently",
      "hit child with belt",
      "bruises on baby face",
    ],
  },
  {
    category: "neglect",
    phrases: [
      "left baby alone at home",
      "left baby alone",
      "no food in house for kids",
      "hungry no food for days",
      "kids have had no food",
      "living in filth",
      "unattended child",
      "no food for toddler for days",
      "left in freezing cold room",
    ],
  },
  {
    category: "domestic_abuse",
    phrases: [
      "partner hurts me",
      "scared of my husband",
      "domestic violence with children",
      "partner threatening me",
      "hit me in front of kids",
      "raped me",
      "raped",
      "partner locked me in room",
      "partner smashed my phone",
      "partner holding knife",
      "stalking me with kids",
      "threatened to kill my family",
      "forced sexual act",
      "monitoring my messages",
      "threatens to take kids away",
    ],
  },
  {
    category: "child_sexual_abuse_grooming",
    phrases: [
      "inappropriate touching",
      "child touched private parts",
      "online grooming",
      "older adult asking for pictures",
    ],
  },
  {
    category: "parental_substance_incapacitation",
    phrases: [
      "too drunk to look after baby",
      "passed out drugs with baby alone",
      "passed out and cant look after baby",
      "passed out and can t look after baby",
      "drank a bottle",
      "too drunk to care",
    ],
  },
  {
    category: "parental_mental_health_crisis",
    phrases: [
      "scared i might hurt baby",
      "scared i might hurt my baby",
      "intrusive thoughts about harming my child",
      "intrusive thoughts about harming child",
      "i have postpartum psychosis",
      "i think i have postpartum psychosis",
      "postnatal psychosis",
      "disconnected from reality",
      "postpartum depression cannot cope",
      "hearing voices telling me",
      "hallucinating and alone with baby",
      "scared i will hurt my newborn",
    ],
  },
  {
    category: "fgm_forced_marriage",
    phrases: [
      "female genital mutilation",
      "fgm",
      "cutting girls",
      "get my daughter cut",
      "forced marriage",
      "forced to marry",
    ],
  },
  {
    category: "childline_direct_disclosure",
    phrases: [
      "my parents hate me",
      "my mum and dad hate me",
      "i am scared of my dad",
      "i want to run away from home",
      "i want to run away",
      "home does not feel safe i want to leave",
    ],
  },
]);
